#pragma once

typedef enum TtyuiBackgroundColor {
    TTYUI_COLOR_BACKGROUND_DEFAULT = 49,
    TTYUI_COLOR_BACKGROUND_WHITE = 47,
    TTYUI_COLOR_BACKGROUND_BLACK = 40,
    TTYUI_COLOR_BACKGROUND_RED = 41,
    TTYUI_COLOR_BACKGROUND_GREEN = 42,
    TTYUI_COLOR_BACKGROUND_YELLOW = 43,
    TTYUI_COLOR_BACKGROUND_BLUE = 44,
    TTYUI_COLOR_BACKGROUND_MAGENTA = 45,
    TTYUI_COLOR_BACKGROUND_CYAN = 46,
} TtyuiBackgroundColor;

typedef enum TtyuiForegroundColor {
    TTYUI_COLOR_FOREGROUND_DEFAULT = 39,
    TTYUI_COLOR_FOREGROUND_WHITE = 37,
    TTYUI_COLOR_FOREGROUND_BLACK = 30,
    TTYUI_COLOR_FOREGROUND_RED = 31,
    TTYUI_COLOR_FOREGROUND_GREEN = 32,
    TTYUI_COLOR_FOREGROUND_YELLOW = 33,
    TTYUI_COLOR_FOREGROUND_BLUE = 34,
    TTYUI_COLOR_FOREGROUND_MAGENTA = 35,
    TTYUI_COLOR_FOREGROUND_CYAN = 36,
} TtyuiForegroundColor;
